=== smart-data-models/dataModel.GBFS/system_calendar/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://smart-data-models.github.io/dataModel.GBFS/system_calendar/schema.json",
  "description": "Describes the operating calendar for a system. According to the Standard GBFS 2.2",
  "modelTags": "GBFS",
  "type": "object",
  "$schemaVersion": "0.0.1",
  "title": "Smart Data Models adaptation of GBFS standard data model system_calendar",
  "properties": {
    "id": {
      "$ref": "https://github.com/smart-data-models/data-models/raw/master/common-schema.json#/definitions/EntityIdentifierType"
    },
    "type": {
      "type": "string",
      "description": "Property. NGSI entity type. It has to be system_calendar",
      "enum": [
        "system_calendar"
      ]
    },
    "last_updated": {
      "description": "Property. Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description": "Property. Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "Property. GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "enum": [
        "1.1-RC",
        "1.1",
        "2.0-RC",
        "2.0",
        "2.1-RC",
        "2.1-RC2",
        "2.1",
        "2.2",
        "3.0-RC",
        "3.0"
      ]
    },
    "data": {
      "description": "Property. Array that contains opertions calendar for the system.",
      "type": "object",
      "properties": {
        "calendars": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "start_month": {
                "description": "Starting month for the system operations.",
                "type": "number",
                "minimum": 1,
                "maximum": 12
              },
              "start_day": {
                "description": "Starting day for the system operations.",
                "type": "number",
                "minimum": 1,
                "maximum": 31
              },
              "start_year": {
                "description": "Starting year for the system operations.",
                "type": "number",
                "pattern": "^\\d{4}$"
              },
              "end_month": {
                "description": "End month for the system operations.",
                "type": "number",
                "minimum": 1,
                "maximum": 12
              },
              "end_day": {
                "description": "End day for the system operations.",
                "type": "number",
                "minimum": 1,
                "maximum": 31
              },
              "end_year": {
                "description": "End year for the system operations.",
                "type": "number",
                "pattern": "^\\d{4}$"
              }
            },
            "required": [
              "start_month",
              "start_day",
              "end_month",
              "end_day"
            ]
          }
        }
      },
      "required": [
        "calendars"
      ]
    }
  },
  "required": [
    "last_updated",
    "ttl",
    "version",
    "data",
    "id",
    "type"
  ]
}

=== smart-data-models/dataModel.GBFS/system_calendar/examples/example.json
{
  "id": "urn:ngsi-ld:system_calendar:id:FNNO:60592292",
  "type": "system_calendar",
  "last_updated": 1604333830,
  "ttl": 86400,
  "version": "3.0",
  "data": {
    "calendars": [
      {
        "start_month": 4,
        "start_day": 1,
        "start_year": 2020,
        "end_month": 11,
        "end_day": 5,
        "end_year": 2020
      }
    ]
  }
}
