=== smart-data-models/dataModel.GBFS/system_regions/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://smart-data-models.github.io/dataModel.GBFS/system_regions/schema.json",
  "description": "Describes regions for a system that is broken up by geographic or political region. According to the Standard GBFS 2.2",
  "type": "object",
  "modelTags": "GBFS",
  "$schemaVersion": "0.0.1",
  "title": "Smart Data Models adaptation of GBFS standard data model system_regions",
  "properties": {
    "id": {
      "$ref": "https://github.com/smart-data-models/data-models/raw/master/common-schema.json#/definitions/EntityIdentifierType"
    },
    "type": {
      "type": "string",
      "description": "Property. NGSI entity type. It has to be system_regions",
      "enum": [
        "system_regions"
      ]
    },
    "last_updated": {
      "description": "Property. Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description": "Property. Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "Property. GBFS version number to which the feed conforms, according to the versioning framework (added in v1.1).",
      "type": "string",
      "enum": [
        "1.1-RC",
        "1.1",
        "2.0-RC",
        "2.0",
        "2.1-RC",
        "2.1-RC2",
        "2.1",
        "2.2",
        "3.0-RC",
        "3.0"
      ]
    },
    "data": {
      "type": "object",
      "description": "Property. Global data about the regions",
      "properties": {
        "regions": {
          "description": "Array of regions.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "region_id": {
                "description": "identifier of the region.",
                "type": "string"
              },
              "name": {
                "description": "Public name for this region.",
                "type": "string"
              }
            },
            "required": [
              "region_id",
              "name"
            ]
          }
        }
      },
      "required": [
        "regions"
      ]
    }
  },
  "required": [
    "data",
    "id",
    "last_updated",
    "ttl",
    "type",
    "version"
  ]
}

=== smart-data-models/dataModel.GBFS/system_regions/examples/example.json
{
  "id": "urn:ngsi-ld:system_regions:id:FNNO:60592292",
  "type": "system_regions",
  "last_updated": 1604332380,
  "ttl": 86400,
  "version": "3.0",
  "data": {
    "regions": [
      {
        "name": "North",
        "region_id": "3"
      },
      {
        "name": "East",
        "region_id": "4"
      },
      {
        "name": "South",
        "region_id": "5"
      },
      {
        "name": "West",
        "region_id": "6"
      }
    ]
  }
}
