=== smart-data-models/dataModel.GBFS/vehicle_types/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://smart-data-models.github.io/dataModel.GBFS/vehicle_types/schema.json",
  "description": "Describes the types of vehicles that System operator has available for rent (added in v2.1-RC). According to the Standard GBFS 2.2",
  "type": "object",
  "modelTags": "GBFS",
  "$schemaVersion": "0.0.1",
  "title": "Smart Data Models adaptation of GBFS standard data model vehicle_types",
  "properties": {
    "id": {
      "$ref": "https://github.com/smart-data-models/data-models/raw/master/common-schema.json#/definitions/EntityIdentifierType"
    },
    "type": {
      "type": "string",
      "description": "Property. NGSI entity type. It has to be vehicle_types",
      "enum": [
        "vehicle_types"
      ]
    },
    "last_updated": {
      "description": "Property. Last time the data in the feed was updated in POSIX time.",
      "type": "integer",
      "minimum": 1450155600
    },
    "ttl": {
      "description": "Property. Number of seconds before the data in the feed will be updated again (0 if the data should always be refreshed).",
      "type": "integer",
      "minimum": 0
    },
    "version": {
      "description": "Property. GBFS version number to which the feed conforms, according to the versioning framework.",
      "type": "string",
      "enum": [
        "2.1-RC",
        "2.1",
        "2.2",
        "3.0-RC",
        "3.0"
      ]
    },
    "data": {
      "description": "Property. Response data in the form of name:value pairs.",
      "type": "object",
      "properties": {
        "vehicle_types": {
          "description": "Array that contains one object per vehicle type in the system as defined below.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "vehicle_type_id": {
                "description": "Unique identifier of a vehicle type.",
                "type": "string"
              },
              "form_factor": {
                "description": "The vehicle's general form factor.",
                "type": "string",
                "enum": [
                  "bicycle",
                  "car",
                  "moped",
                  "other",
                  "scooter"
                ]
              },
              "propulsion_type": {
                "description": "The primary propulsion type of the vehicle.",
                "type": "string",
                "enum": [
                  "human",
                  "electric_assist",
                  "electric",
                  "combustion"
                ]
              },
              "max_range_meters": {
                "description": "The furthest distance in meters that the vehicle can travel without recharging or refueling when it has the maximum amount of energy potential.",
                "type": "number",
                "minimum": 0
              },
              "name": {
                "description": "The public name of this vehicle type.",
                "type": "string"
              }
            },
            "required": [
              "vehicle_type_id",
              "form_factor",
              "propulsion_type"
            ]
          },
          "if": {
            "properties": {
              "propulsion_type": {
                "const": [
                  "electric",
                  "electric_assist",
                  "combustion"
                ]
              }
            }
          },
          "then": {
            "properties": {
              "max_range_meters": {
                "required": [
                  "max_range_meters"
                ]
              }
            }
          }
        }
      },
      "required": [
        "vehicle_types"
      ]
    }
  },
  "required": [
    "data",
    "id",
    "last_updated",
    "ttl",
    "type",
    "version"
  ]
}

=== smart-data-models/dataModel.GBFS/vehicle_types/examples/example.json
{
  "id": "urn:ngsi-ld:vehicle_types:id:FNNO:60592292",
  "type": "vehicle_types",
  "last_updated": 1609866247,
  "ttl": 0,
  "version": "3.0",
  "data": {
    "vehicle_types": [
      {
        "vehicle_type_id": "abc123",
        "form_factor": "bicycle",
        "propulsion_type": "human",
        "name": "Example Basic Bike",
        "default_reserve_time": 30,
        "return_type": [
          "any_station",
          "free_floating"
        ],
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_bicycle.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_bicycle_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "bike_plan_1",
        "pricing_plan_ids": [
          "bike_plan_1",
          "bike_plan_2",
          "bike_plan_3"
        ]
      },
      {
        "vehicle_type_id": "def456",
        "form_factor": "scooter",
        "propulsion_type": "electric",
        "name": "Example E-scooter V2",
        "default_reserve_time": 30,
        "max_range_meters": 12345,
        "return_type": [
          "free_floating"
        ],
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_escooter.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_escooter_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "scooter_plan_1"
      },
      {
        "vehicle_type_id": "car1",
        "form_factor": "car",
        "propulsion_type": "combustion",
        "name": "Four-door Sedan",
        "default_reserve_time": 0,
        "max_range_meters": 523992,
        "return_type": [
          "roundtrip_station"
        ],
        "vehicle_assets": {
          "icon_url": "https://www.example.com/assets/icon_car.svg",
          "icon_url_dark": "https://www.example.com/assets/icon_car_dark.svg",
          "icon_last_modified": "2021-06-15"
        },
        "default_pricing_plan_id": "car_plan_1"
      }
    ]
  }
}
